version: '3.6'
services:
  app:
    image: gcr.io/google-appengine/php72:latest
    container_name: ${APP_CONTEAINER_NAME}
    volumes:
      - ${APP_LOCAL_DIR}:/app
      - ./app/nginx:/etc/nginx
    ports:
      - ${APP_WEB_PORT}:8080
      - ${APP_DATASTORE_PORT}:8000
    environment:
      - DOCUMENT_ROOT=${APP_DOCUMENT_ROOT}
      - CI_ENV=${APP_CI_ENV}
      - DATASTORE_EMULATOR_HOST=${APP_DATASTORE_EMULATOR_HOST}
      - GOOGLE_APPLICATION_CREDENTIALS=${APP_GOOGLE_APPLICATION_CREDENTIALS}
      - GOOGLE_PROJECT_ID=${APP_GOOGLE_PROJECT_ID}
  gcloud:
    image: google/cloud-sdk:latest
    container_name: ${GCP_CONTEAINER_NAME}
    volumes:
      - ${APP_LOCAL_DIR}:/app
      - ./gcloud/.config:${GCP_CLOUD_SDK_CONFIG}
    environment:
      - CLOUD_SDK_VERSION=${GCP_CLOUD_SDK_VERSION}
    tty: true
